# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newapi < Formula
  desc "CLI for new-api gateways"
  homepage "https://github.com/Xbang0222/new-api-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.0/new-api-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "0cc6a3821ce4551bbc88df7ee9c47f7679c1a67fe5bc8df1bbc1b3b732e3936e"

      define_method(:install) do
        bin.install "newapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.0/new-api-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "ca656e38f9106c5f1a405d2de8b70405aec90a23888b7bcedfc8dea00e47c549"

      define_method(:install) do
        bin.install "newapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.0/new-api-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "1fe15e563e09fe19537590d6c7af5b56bbe269050aa1db8a31a6f4e1fbcd145b"
      define_method(:install) do
        bin.install "newapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.0/new-api-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "2a5bce65b52e3906b5ec973c22ebc9ce8d33970f8eeb8f3755d0b0f3a82a818a"
      define_method(:install) do
        bin.install "newapi"
      end
    end
  end
end
