# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newapi < Formula
  desc "CLI for new-api gateways"
  homepage "https://github.com/Xbang0222/new-api-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.1/new-api-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "56b0d14d485fbc0520c61b8575a2c5e325a53e168d128b82651e4ab7bd73c8ad"

      define_method(:install) do
        bin.install "newapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.1/new-api-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "e1cd2ae0724624ff356bb91b48a9e66707a0f473bad3f61b72c47533839a98d0"

      define_method(:install) do
        bin.install "newapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.1/new-api-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "c22d0185d16a088c9cd958f37d8470c5cae2da835bcaaa6d071658cfcc286bb1"
      define_method(:install) do
        bin.install "newapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Xbang0222/new-api-cli/releases/download/v0.1.1/new-api-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "ee42e872eb6aed06099acda4c185b0c58460b836963f693be5318fe5d9c60d1e"
      define_method(:install) do
        bin.install "newapi"
      end
    end
  end
end
